FIND_PATH(SPARSEHASH_INCLUDE_DIRS sparsehash/sparse_hash_map)

IF (SPARSEHASH_INCLUDE_DIRS)
  FIND_PATH(SPARSEHASH_INCLUDE_DIRS google/sparse_hash_map)
ENDIF (SPARSEHASH_INCLUDE_DIRS)

IF (SPARSEHASH_INCLUDE_DIRS)
  SET(SPARSEHASH_FOUND TRUE)
ENDIF (SPARSEHASH_INCLUDE_DIRS)


IF (SPARSEHASH_FOUND)
  IF (NOT SPARSEHASH_FIND_QUIETLY)
    MESSAGE(STATUS "Found sparsehash")
  ENDIF (NOT SPARSEHASH_FIND_QUIETLY)
ELSE (SPARSEHASH_FOUND)
  IF (SPARSEHASH_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find sparsehash")
  ENDIF (SPARSEHASH_FIND_REQUIRED)
ENDIF (SPARSEHASH_FOUND)
