FIND_PATH(RAPIDJSON_INCLUDE_DIRS rapidjson/rapidjson.h)

IF (RAPIDJSON_INCLUDE_DIRS)
  SET(RAPIDJSON_FOUND TRUE)
ENDIF (RAPIDJSON_INCLUDE_DIRS)


IF (RAPIDJSON_FOUND)
  IF (NOT RAPIDJSON_FIND_QUIETLY)
    MESSAGE(STATUS "Found RapidJSON")
  ENDIF (NOT RAPIDJSON_FIND_QUIETLY)
ELSE (RAPIDJSON_FOUND)
  IF (RAPIDJSON_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find RapidJSON")
  ENDIF (RAPIDJSON_FIND_REQUIRED)
ENDIF (RAPIDJSON_FOUND)
